### ISSUE TITLE
Possibly allow for arbitrary config file name

### ISSUE THREAD

**Issue by oalders** [houseabsolute/precious#13]
I introduced a `precious.toml` file internally at $work and there was a suggestion to use `.precious.toml` in order to hide the file from the people who aren't yet using the tool. It would be nice to allow for an arbitrary config file name to be supplied or at least for a config file to have a leading dot.

I could work on this if it's something you're amenable to.

**Comment by autarch** [comment]
I'm open to a `--config/-c` flag for the main command. I think it'd _also_ be fine to have it check for both `precious.toml` and `.precious.toml` when it looks for a config file.

**Comment by autarch** [comment]
Done in v0.1.3
