### ISSUE TITLE
dependency on which is needlessly strict

### ISSUE THREAD

**Issue by jonassmedegaard** [houseabsolute/precious#19]
Please consider relaxing dependency on which to allow not only v4 but also v3 [like this](https://salsa.debian.org/debian/precious/-/blob/debian/latest/debian/patches/1003_which.patch) - or if for some reason that's not supposed to work then I suggest extending tests to cover that, because it succeeds fine for me (and has helped reduce the need for embedded libraries with the packaging).

**Comment by autarch** [comment]
Could you make one PR with all of these dependency changes?

**Comment by jonassmedegaard** [comment]
Sorry, I won't push any code to Github due to [their ToS suspected of undermining copyleft licensing](https://joeyh.name/blog/entry/removing_everything_from_github/) but if that's helpful you can do this:
```bash
git remote add salsa https://salsa.debian.org/debian/precious.git
git fetch --no-tags salsa
git cherry-pick wip/relax_deps
```

**Comment by jonassmedegaard** [comment]
No rush. Thanks anyway.
