### ISSUE TITLE
Precious should print stdout on unexpected exit code even if there is no stderr

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/precious#28]
This is a follow-up to #26. The particular linter I am running into this with is `golangci-lint`, which outputs to stdout. You can reproduce this with the test script from #26 but removing the line that outputs to stderr.

I'd be happy to submit a PR, but I suspect some refactoring might make sense as I don't know if it makes sense to distinguish between `UnexpectedExitCode` and `UnexpectedExitCodeWithStderr` or, if it does, maybe there should be four separate enum values for the four combinations.

**Comment by autarch** [comment]
I just pushed a branch named `command-output` that changes this. If a command exits with an unexpected code and has either stdout or stderr, you'll always see that. I also tweaked exactly how the error was formatted so it says if one of stdout or stderr was empty.

**Comment by autarch** [comment]
I also combined those two error variants into just one. I agree that this makes more sense.

**Comment by oschwald** [comment]
Thanks!

**Comment by autarch** [comment]
Fixed in v0.1.7.

**Comment by oschwald** [comment]
Thanks again.

While reviewing the changes, I saw that your commits signed with your SSH key are "unverified". GitHub [recently added SSH commit verification](https://github.blog/changelog/2022-08-23-ssh-commit-verification-now-supported/).  You just need to add your public key as a signing key.

**Comment by autarch** [comment]
> While reviewing the changes, I saw that your commits signed with your SSH key are "unverified". GitHub [recently added SSH commit verification](https://github.blog/changelog/2022-08-23-ssh-commit-verification-now-supported/). You just need to add your public key as a signing key.

Yeah, I'm confused about this. The key it says is unverified was already in my profile.

**Comment by autarch** [comment]
Aha, I have to add it _again_ as a signing key. That fixed it.
