### ISSUE TITLE
Stashing with --staged should be optional

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/precious#30]
We have had a number of problems when using `--staged` in Git pre-hooks, including:

1. The appearance and disappearance of files can leave editors in confused states.
2. If someone working directory is new, a `git commit` can cause that directory to be deleted and a new one created with the same name forcing them to switch to the new directory in their shell.
3. If someone ctrl-c's during a commit, the repo can be left in a broken state. In most cases, popping the stash is enough to fix it, but it isn't immediately obvious that this needs to be done, leading to a lot of confusion and possibly lost work.

We tried using the `--git` flag instead, but this doesn't work as it doesn't pass the `--cached` flag to `git diff`, making `precious` think no files have changed.

For the time being, we will probably work around this by passing our own list of files to `precious`, but this seems like a suboptimal experience.

**Comment by autarch** [comment]
This is done in #30. The `--staged` flag will no longer stash anything. To get the old behavior you can call `--staged-with-stash`, But I've experienced some of the same issues you describe with stashing, so I may remove that flag entirely at some point.

**Comment by oschwald** [comment]
Thanks!
