### ISSUE TITLE
Adding the ability to run a single command

### ISSUE THREAD

**Issue by oalders** [houseabsolute/precious#31]
Right now we've got a `precious.toml` that has 17 commands and will soon have more. Occasionally, if a command changes or is added, I'll need to run `precious tidy --all`. It would be faster and more efficient to be able to run a single command rather than current approach. My workaround is to edit the config to comment out the parts I don't want to run. I'm happy to try to create a PR for this if that's helpful.

**Comment by oalders** [comment]
In our config it's all `[commands.binary-descriptivename]`, so I hadn't considered spaces, which wouldn't look great.

I suppose it could be something along the lines of "if you want to run a single command, don't use spaces in the command" or possibly adding something along these lines to allow a fallback:

```toml
[commands."some long string here"]
alias = "command-name-to-use-as-argument"
```

Having said that, I'm not clear on why you'd need the spaces in the command name. If you need something descriptive you could add a comment or there could be a description/documentation key on the command config to allow you to do that.

**Comment by autarch** [comment]
This is done in v0.2.2.

**Comment by oalders** [comment]
Thank you!!!
