### ISSUE TITLE
LICENSE-MIT is the Apache 2.0 license

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/precious#33]
I was looking at the repo and I noticed this:

![image](https://user-images.githubusercontent.com/278835/192074210-38fd583c-3d9c-40ef-9a8e-fda92c1d6cb8.png)

Looking at the license files, it appears `LICENSE-MIT` is actually the full Apache 2.0 license. `LICENSE-APACHE` is the Apache 2.0 license header.

**Comment by autarch** [comment]
Oops, I will fix this. Thanks.

**Comment by autarch** [comment]
This is fixed.
