### ISSUE TITLE
Confusing output from precious

### ISSUE THREAD

**Issue by oalders** [houseabsolute/precious#35]
Was [this](https://github.com/houseabsolute/precious/blob/4dc0dec3dd3f998f9b2e9a39be84196197f12a20/precious-core/src/config.rs#L266) left over debugging code? I'm finding it's emitting some confusing output.

```bash
precious tidy --command mypy pylib/foo.py
💍 Tidying paths passed on the command line (recursively)
Tidy != Lint
Tidy != Lint
Tidy != Lint
Tidy != Lint
Tidy != Lint
[precious_core::precious][ERROR] Failed to run precious: No tidying commands match the given command name, mypy
```

**Comment by autarch** [comment]
Yes, this is left over debugging. It'll be gone in the next release.

**Comment by autarch** [comment]
Fixed in v.0.2.3
