### ISSUE TITLE
Add a command to emit all of the command names in the config

### ISSUE THREAD

**Issue by oalders** [houseabsolute/precious#52]
I've got a config file which is > 870 lines long and it's a bit of a pain for me to root around for all of the available commands. Would it be reasonable to add something like:

`precious config --commands` to emit a list of available commands?

Maybe allow for constraining them by type as well?

`precious config --commands --type lint|tidy|both`

**Comment by autarch** [comment]
Yes, off hand that seems like a reasonable thing to add. Also, I'd love to see this config file!

**Comment by oalders** [comment]
This is for $work, but it has 42 different commands. Some of these include:

```text
[commands.git-diff-check]
[commands.ppath]
[commands.black]
[commands.clang-format]
[commands.go-generate]
[commands.go-generate-xgb]
[commands.golines]
[commands.golangci-lint]
[commands.perlcritic]
[commands.perlcritic-untypedrouteplaceholders]
[commands.perlvars]
[commands.perlimports]
[commands.perltidy]
[commands.dprint]
[commands.eslint]
[commands.prettier]
[commands.omegasort]
[commands.shellcheck]
[commands.shfmt]
[commands.terraform-fmt]
[commands.yamllint]
[commands.mypy]
[commands.pylint]
[commands.newline]
```

Some of the commands are duplicated with slight variations as they may run out of different directories with slightly different config files (like for `eslint`). I'm about to add at least one more command in some work I'm doing today, so I assume this file will only get bigger.

**Comment by autarch** [comment]
It occurs to me that another option might be to allow precious to read _multiple_ files. Then you could have one per language. The option to print out the commands might still be useful, of course.

**Comment by oalders** [comment]
I feel like I'm already drowning in config files, so I'm not sure how I feel about breaking up the `precious` config into multiple files. 🤔

Was there talk of adding tags or groups at one point? If I could say `precious tidy --tag javascript`, that might prevent me from having to snoop around the config in a lot of cases as well.

**Comment by autarch** [comment]
> I feel like I'm already drowning in config files, so I'm not sure how I feel about breaking up the `precious` config into multiple files. 🤔

Fair point.

> Was there talk of adding tags or groups at one point? If I could say `precious tidy --tag javascript`, that might prevent me from having to snoop around the config in a lot of cases as well.

That already exists! Search for "labels" in the docs.

**Comment by oalders** [comment]
> That already exists! Search for "labels" in the docs.

Nice! I added some labels today. That's already a big help. I think I was searching on `tag`, so I was coming up empty.

**Comment by autarch** [comment]
Here's my first draft of `precious config list` output:

```
Found config file at: /home/autarch/projects/precious/precious.toml

It contains the following commands:
  rustfmt: type = "both"
    runs "rustfmt"
  clippy: type = "lint"
    runs "cargo"
  prettier: type = "both"
    runs "./node_modules/.bin/prettier"
  omegasort-gitignore: type = "both"
    runs "omegasort"
```

What do you think?

**Comment by autarch** [comment]
I wonder if adding a blank line between commands would be good. It'd make it much longer in your case, but maybe it's worth the additional readability?

**Comment by autarch** [comment]
Or the fancy version:

```
┌─────────────────────┬────────┬──────────────────────────────┐
│ Name                ┆ Type   ┆ Runs                         │
╞═════════════════════╪════════╪══════════════════════════════╡
│ rustfmt             ┆ "both" ┆ rustfmt                      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ clippy              ┆ "lint" ┆ cargo                        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ prettier            ┆ "both" ┆ ./node_modules/.bin/prettier │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ omegasort-gitignore ┆ "both" ┆ omegasort                    │
└─────────────────────┴────────┴──────────────────────────────┘
```

**Comment by oalders** [comment]
The fancy version looks great! I find that much easier to read.

**Comment by autarch** [comment]
Done in v0.5.2.

**Comment by oalders** [comment]
Thank you so much!

**Comment by danielcompton** [comment]
@oalders are you able to share your config file? In particular I'm interested in the terraform part.

**Comment by oalders** [comment]
@danielcompton I can't really share the whole thing as it's for $work, but the terraform config is essentially:

```
[commands.terraform-fmt]
type = "both"
cmd = ["terraform", "fmt"]
ok-exit-codes = 0
lint-flags = ["--check"]
include = ["path-to-terraform/**/*.tf"]
```
