### ISSUE TITLE
When generating go config a `golangci-lint.yml` file should also be generated

### ISSUE THREAD

**Issue by autarch** [houseabsolute/precious#59]
Without this the generated config won't do anything.

**Comment by autarch** [comment]
Done in v0.6.1.

**Comment by oalders** [comment]
Just wanted to point out that this does deviate from the default config names. Not sure it matters so much.

https://golangci-lint.run/usage/configuration/#config-file

> Config File
GolangCI-Lint looks for config files in the following paths from the current working directory:
>
> .golangci.yml
> .golangci.yaml
> .golangci.toml
> .golangci.json
