### ISSUE TITLE
Add a `--git-modified-in-branch <branch>` file selector

### ISSUE THREAD

**Issue by autarch** [houseabsolute/precious#64]
If someone would like to lint a branch with multiple commits on it, there's no easy way to pick just the modified files. This means they probably need to use `--all`, which can be much slower than picking a few files.

We can support this with a new file selector option, `--git-modified-in-branch`. Getting the list of files is simple. Just run `git diff --name-only <branch>...`.

TODO: Is this is the best name for this option?

**Comment by mmcclimon** [comment]
> TODO: Is this is the best name for this option?

I would call it `--git-modified-since`, because git diff can take an arbitrary commit/tree-ish. I can imagine doing `--git-modified-since HEAD~6` or something.

**Comment by autarch** [comment]
I ended up going with `--git-diff-from` because the word "since" implies that it's based on time. If you're up for it, could you test out a pre-release binary and see if this does what you expect? You can see the binaries at the bottom of https://github.com/houseabsolute/precious/actions/runs/8306574501.

**Comment by mmcclimon** [comment]
This is great, thanks! (Thank you also for giving it a short option.)

**Comment by autarch** [comment]
This is done in v0.6.4 release.
